# Generated by Django 6.0 on 2025-12-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('TV Show', 'TV Show')], max_length=10)),
                ('release_year', models.IntegerField()),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='netflix_app.country')),
            ],
            options={
                'db_table': 'title',
            },
        ),
        migrations.CreateModel(
            name='TitleActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.actor')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.title')),
            ],
            options={
                'db_table': 'title_actor',
            },
        ),
        migrations.CreateModel(
            name='TitleDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.director')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.title')),
            ],
            options={
                'db_table': 'title_director',
            },
        ),
        migrations.CreateModel(
            name='TitleGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.genre')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.title')),
            ],
            options={
                'db_table': 'title_genre',
            },
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['release_year'], name='title_release_7da084_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['type'], name='title_type_75c54f_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['country'], name='title_country_a861e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='titleactor',
            constraint=models.UniqueConstraint(fields=('title', 'actor'), name='uq_title_actor'),
        ),
        migrations.AddConstraint(
            model_name='titledirector',
            constraint=models.UniqueConstraint(fields=('title', 'director'), name='uq_title_director'),
        ),
        migrations.AddConstraint(
            model_name='titlegenre',
            constraint=models.UniqueConstraint(fields=('title', 'genre'), name='uq_title_genre'),
        ),
    ]
